title:             Visiting University of Azores
email:             koe@cphbusiness.dk
description:       A blog on a visit to teach blender and python
author:            Kasper Ã˜sterbye
baseurl:           "/KasperAtAzores"
url:               "http://kaspercphbusiness.github.io"

# Social Profiles
twitter_username:  
github_username:   kaspercphbusiness
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
